#########Makefile For ZUK_Z2#########

Branch := Flyme_M_base
Android_Version := M
WangUI_Version := 3.1.x Developer Preview

META_FILES := common/META

#You should Gen a key by yourself at chain/
PRIVATE_KEY := chain/build.pk8
CERTIFICATE := chain/build.x509.pem

BOOTIMAGE := bootimage/bootimage

#End of this file