#########Makefile For ZUK_Z2#########

Branch := Flyme_M_base
Android_Version := M
WangUI_Version := 3.1.x Developer Preview

META_FILES := common/META

PRIVATE_KEY := chain/build.pk8
CERTIFICATE := chain/build.x509.pem

BOOTIMAGE := bootimage/bootimage

SYSTEM_PROP := system.prop

#Pre_Unpack bootimage's file
PRE_UNPACK_BOOTIMAGE := bootimage.out/

#End of this file